### ISSUE TITLE
Record fields with underscores give TH machinery trouble

### ISSUE THREAD

**Issue by ozataman** [lykahb/groundhog#29]
The below yields a large error complaining about:

```
    Illegal data constructor"
<- " name: `_pgHostField'
    When splicing a TH declaration:
      instance Database.Groundhog.Core.PersistEntity Compute.Backends.PGCommon.PGConfig
    where data Database.Groundhog.Core.Key Compute.Backends.PGCommon.PGConfig
```

Example code:

```
data PGConfig = PGConfig
    { _pgHost     :: Text
    , _pgPort     :: Int
    , _pgUser     :: Text
    , _pgPass     :: Text
    , _pgDatabase :: Text
    , _pgSchema   :: Text
    , _pgSSL      :: SSLMode
    } deriving (Eq,Show,Generic)
```

```
- entity: PGConfig
  dbName: xxxxx
  constructors:
    - name: PGConfig
```
