### ISSUE TITLE
Key on embedded field

### ISSUE THREAD

**Issue by yaitskov** [lykahb/groundhog#99]
```
data T1 = T1 { _t1_F1 :: Int }

data T2 = T2 { _t2_F2 :: T1 }

mkPersist(defaultCodegenConfig { namingStyle = escapeUnderscore })
  [groundhog|
definitions:
  - entity: T2
    dbName: t2
    autoKey: null
    keys:
      - name: Xxx
        default: true
    constructors:
      - name: T2
        uniques:
          - name: Xxx
            type: primary
            fields: [_t2_F2._t1_F1]
|]

```

```
    Exception when trying to run compile-time code:
      Not found field with name "_t2_F2._t1_F1"
```
